const muscle=[{val:"abdominals"},
        {val:"abductors"},
        {val:"adductors"},
        {val:"biceps"},
        {val:"calves"},
        {val:"chest"},
        {val:"forearms"},
        {val:"glutes"},
        {val:"hamstrings"},
        {val:"lats"},
        {val:"lower back"},
        {val:"middle back"},
        {val:"neck"},
        {val:"quadriceps"},
        {val:"traps"},
        {val:"triceps"}]
export default muscle;